server:
  port: ${PORT:8082}
spring:
  jackson:
    time-zone: UTC
  datasource:
    initialization-mode: always
    platform: postgres
    url: jdbc:postgresql://${USER_SERVICE_DB_HOST:localhost:5432}/${USER_SERVICE_DB:user_service}
    username: ${USER_SERVICE_DB_USERNAME:user_service}
    password: ${USER_SERVICE_DB_PASSWORD:password}
  jpa:
    show_sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
      generate-ddl: true
journal:
  name: user-service.journal
auth:
  username: ${USER_SERVICE_USERNAME:user_service}
  password: ${USER_SERVICE_PASSWORD:$2y$12$Sr9Zsb.eVzosnkwtOMDfjOVM6YqgPSk/6mpOrbaFXBDExiSVxZlmm} # password
  roles: ADMIN